# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Deploy a new internal test version to the Google Play"
  lane :staging_internal do
    upload_to_play_store(
       track: "internal",
       aab: "../%s" % ENV["SIGNED_RELEASE_FILE"]
    )
  end

  desc "Deploy into production track to the Google Play"
  lane :deploy_production do
    upload_to_play_store(
       track: "production",
       aab: "../%s" % ENV["SIGNED_RELEASE_FILE"]
    )
  end
end
