name: Test CI Dart

on:
  push:
    branches: [ workflowtest ]

jobs:
  deploy_android:
    name: Deploy to Playstore internal test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Flutter tasks
        uses: subosito/flutter-action@v1.3.2
      - run: flutter pub get
      - run: flutter build appbundle --flavor staging
      - name: Sign the app
        id: sign-android-app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: build/app/outputs/bundle/stagingRelease
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_PASS }}
          keyPassword: ${{ secrets.KEY_PASS }}

      - name: Decode json api key and save to a file
        env: 
          JSON_KEY: ${{ secrets.JSON_KEY }}
        run: echo "$JSON_KEY" | base64 --decode > ${HOME}/apikey.json
